CREATE TABLE PERSON(
	Id INTEGER NOT NULL UNIQUE,
	Name VARCHAR(35) NOT NULL,
	Surname VARCHAR(35) NOT NULL,
	Email VARCHAR(35) NOT NULL,
	Cell CHAR(10) NOT NULL,
	Password VARCHAR(20) NOT NULL,
	ModifiedDate DATE NOT NULL,
	PRIMARY KEY(Id)
);

ALTER TABLE PERSON
ADD CONSTRAINT PersonMD DEFAULT CONVERT(DATE, GETDATE()) FOR ModifiedDate;


CREATE TABLE PRODUCT(
	ProdId CHAR(8) NOT NULL UNIQUE,
	SellerId INTEGER NOT NULL,
	Name VARCHAR(35) NOT NULL,
	Description VARCHAR(35),
	Price DECIMAL(2,2) NOT NULL,
	SubCategoryId CHAR(5) NOT NULL,
	ModifiedDate DATE NOT NULL,
	PRIMARY KEY(ProdId),
	FOREIGN KEY(SellerId) REFERENCES SELLER,
	FOREIGN KEY(SubCategoryId) REFERENCES PRODUCTSUBCATEGORY
);

ALTER TABLE PRODUCT
ALTER COLUMN Price DECIMAL(7,2) NOT NULL;


CREATE TABLE PRODUCTCATEGORY(
	CategoryId CHAR(5) NOT NULL UNIQUE,
	Name VARCHAR(35) NOT NULL,
	ModifiedDate DATE NOT NULL,
	PRIMARY KEY(CategoryId)
);


CREATE TABLE PRODUCTSUBCATEGORY(
	SubCategoryId CHAR(5) NOT NULL UNIQUE,
	CategoryId CHAR(5) NOT NULL,
	Name VARCHAR(35) NOT NULL,
	ModifiedDate DATE NOT NULL,
	FOREIGN KEY(CategoryId) REFERENCES PRODUCTCATEGORY,
	PRIMARY KEY(SubCategoryId)
);


CREATE TABLE PRODUCTIMAGE(
	ProductId CHAR(8) NOT NULL,
	ImageId CHAR(5) NOT NULL,
	Location VARCHAR(35) NOT NULL,
	ModifiedDate DATE NOT NULL,
	PRIMARY KEY(ProductId, ImageId)
);

/*
ALTER THE TABLE FOR IMAGE
*/
ALTER TABLE PRODUCTIMAGE
DROP COLUMN Location;

ALTER TABLE PRODUCTIMAGE
ADD Title IMAGE;


CREATE TABLE PRODUCTRATING(
	ProductId CHAR(8) NOT NULL,
	BuyerId INTEGER NOT NULL,
	RatingId CHAR(10) NOT NULL UNIQUE,
	Ratings FLOAT NOT NULL,
	ModifiedDate DATE NOT NULL,
	PRIMARY KEY(RatingId),
	FOREIGN KEY(ProductId) REFERENCES PRODUCT,
	FOREIGN KEY(BuyerId) REFERENCES BUYER
);


CREATE TABLE PRODUCTREVIEW(
	ProductId CHAR(8) NOT NULL,
	BuyerId INTEGER NOT NULL,
	ReviewId CHAR(10) NOT NULL UNIQUE,
	Description VARCHAR(35) NOT NULL,
	ModifiedDate DATE NOT NULL,
	PRIMARY KEY(ReviewId),
	FOREIGN KEY(ProductId) REFERENCES PRODUCT,
	FOREIGN KEY(BuyerId) REFERENCES BUYER
);

ALTER TABLE PRODUCTREVIEW
ALTER COLUMN Description VARCHAR(100) NOT NULL;


CREATE TABLE PRODUCINVENTORY(
	ProductId CHAR(8) NOT NULL,
	Quantity INTEGER NOT NULL,
	SoldQuantity INTEGER,
	ModifiedDate DATE NOT NULL,
	FOREIGN KEY(ProductId) REFERENCES PRODUCT
);

ALTER TABLE CART
ADD CONSTRAINT CartMD DEFAULT CONVERT(DATE, GETDATE()) FOR ModifiedDate;

CREATE TABLE BUYER(
	Id INTEGER NOT NULL,
	BuyerId INTEGER NOT NULL UNIQUE,
	ModifiedDate DATE NOT NULL,
	PRIMARY KEY(BuyerId),
	FOREIGN KEY(Id) REFERENCES PERSON
);


CREATE TABLE SELLER(
	Id INTEGER NOT NULL,
	SellerId INTEGER NOT NULL UNIQUE,
	ModifiedDate DATE NOT NULL,
	PRIMARY KEY(SellerId),
	FOREIGN KEY(Id) REFERENCES PERSON
);


CREATE TABLE CART(
	ProductId CHAR(8) NOT NULL,
	BuyerId INTEGER NOT NULL,
	Quantity INTEGER NOT NULL,
	ModifiedDate DATE NOT NULL,
	PRIMARY KEY(ProductId, BuyerId)
);
